import type { ProductRegistrationStep } from './types';

export const PRODUCT_REGISTRATION_STEPS = {
  IMAGE_UPLOAD: 'imageUpload',
  PRODUCT_ANALYSIS_LOADING: 'productAnalysisLoading',
  PRODUCT_ANALYSIS_RESULT: 'productAnalysisResult',
  ADDITIONAL_INFO: 'additionalInfo',
  PRICE_ANALYSIS_LOADING: 'priceAnalysisLoading',
  PRICE_RESULT: 'priceResult',
  PRICE_EDIT: 'priceEdit',
  CONFIRM: 'confirm',
  COMPLETE: 'complete',
} as const satisfies Record<string, ProductRegistrationStep>;

export const PRODUCT_REGISTRATION_STEP_ORDER = [
  PRODUCT_REGISTRATION_STEPS.IMAGE_UPLOAD,
  PRODUCT_REGISTRATION_STEPS.PRODUCT_ANALYSIS_LOADING,
  PRODUCT_REGISTRATION_STEPS.PRODUCT_ANALYSIS_RESULT,
  PRODUCT_REGISTRATION_STEPS.ADDITIONAL_INFO,
  PRODUCT_REGISTRATION_STEPS.PRICE_ANALYSIS_LOADING,
  PRODUCT_REGISTRATION_STEPS.PRICE_RESULT,
  PRODUCT_REGISTRATION_STEPS.PRICE_EDIT,
  PRODUCT_REGISTRATION_STEPS.CONFIRM,
  PRODUCT_REGISTRATION_STEPS.COMPLETE,
] as const;